package admi.buildeeji.activity;

/**
 * Created by Admin on 8/16/2016.
 */
public class StringArraysClass {
    // Basic BuildExpo project
    public static final String[] companyNameBasic = {"L&T Infocity Ltd ", " PRAJAPATI CONSTRUCTIONS ", " ADITYA CONSTRUCTIONS ", "ANIRUDH CONSTRUCTIONS ", " ANUSHA INFRASTRUCTURE ", "APARNA CONSTUCTIONS PVT LTD ", " APURUPA INFRASTRUCTURS PVT LTD ", " ASHOKA DEVELOPERS&BUILDERS LTD ", " AVIGHNA CONSTRUCTIONS ", " AZ DEVELOPERS ", " BABUKHAN PROPERTIES ", " BJSM ENGG CONSULTANTS&BUILDERS ", " DHAATRI CONSTRUCTION PVT LTD ", " DREAM VALLEY RESORTS ", " ESSEN INFRA ", " IL&FS ENGG AND CONSTRUCTION LTD ", " IVRCL PVT LTD ", " KEERTHANA CONSTRUCTIONS ", " LOUTUS PROPERTIES LTD ", " MAK INFRASTRUCTURE HOUSING DEVELOPERS ", " MANISHA CONSTRUCTIONS PVT LTD ", " MARUTHI CORPORATION LTD "};
    public static final String[] contactPersonBasic = {"KUNA SHANKAR ", " GOPINATH ", " B.RAVINDHERRAO  ", " J.CHAKRAVARTHY ", " MOHAN REDDY ", " SURYA RAO  ", " ANIL REDDY  ", " N.JAIDEEP REDDY ", " MAHESH ", " SRINIVAS/ZULFI RAVDZE  ", " MANOSOOR/MUSTAFA ", " S.A.BABAR ", " MALLIKARJUNA REDDY ", " RAMA RAO  ", " SACHITANANDA REDDY ", " ANIL K AGARWAL ", " NANDA KISHOR ", " MANISHWARA RAO ", " B.SUDHAKAR RAO ", " MURALI KRISHNA REDDY ", " RAGHU KUMAR  ", " RAM REDDY "};
    public static final String[] phoneBasic = {" 040-23110217 ", " 9246842843 ", " 23393695 ", " 9246222018 ", " 9848799570 ", " 23352708 ", " 9848032583 ", " 9908237272 ", " 9866800043 ", " 9908524483 ", " 9246525257 ", " 9849467869 ", " 23300051 ", " 66782686 ", " 9949683338 ", " 40409333 ", " 23356613 ", " 9391333526 ", " 9246171500 ", " 23415500 ", " 23376677 ", " 9848057666 "};
    public static final String[] emailBasic = {" info@intecc.com ", " sales@prajapatigroup.com ", " adityaconstructions@rediffmail.com  ", " jwala.chakravarthy@gmail.com ", " mohanreddy29@yahoo.co.in ", " info@aparnaconstructions.com ", " apurupainfra@gmail.com ", " info@ashokabuilders.com ", " azdevelopers@yahoo.co.in ", " sales@babukhanproperties.com ", " babar2007123@yahoo.com ", " info@dhaatrigroup.com ", " info@dreamvalleygroup.com ", " sadinimma@gmail.com ", " info@ilfsengg.com ", " info@ivrinfra.com ", " info@lpl.co.in ", " frontdesk@makprojects.com ", " manishaconstructons@yahoo.com ", " maruthicorp@gmail.com ", " info@intecc.com ", " frontdesk@makprojects.com "};

    //Normal BuildExpo

    //Normal BuildExpo project
    public static final String[] companyNameNormal = {" NAMRA CONSTRUCTIONS PVT LTD ", " OAKWOOD BUILDERS ", " PRAGATI GREEN MEADOWS ", " RK ESTATES ", " ROYAL HOME CONSTRUCTIONS ", " SRI ADITYA HOMES PVT LTD ", " SRINIVASA CONSTRUCTIONS LTD ", " SRR PROJECTS public LIMITED ", " UMA ESTATES INFRASTRUCTURE PVT LTD  ", " VH  INFRASTRUCTURS&PROJECTS PVT LTD ", " ADITYA CONSTRUCTION COMPANY INDIA PVT ", " BHAVYA CONSTRUCTIONS PVT LTD ", " CHOICE INDIA PRIJECTS PVT LTD  ", " GIRIDHARI CONTRUCTIONS ", " GREENVIEW INFRA PROJECTS INDIA PVT LTD ", " HEADYWAY PROPERTIES PVT LTD ", " IVRCL LTD ", " MADHUCON PROJECTS LTD ", " MAHINDHARA PROJECTS PVT LTD ", " MEENAKSHI INFRASTRUCTURES PVT LTD "};
    public static final String[] contactPersonNormal = {" RAFATHULLAH KHAN ", " IMAD ", " G.B.K RAO ", " JAYA PRAKASH ", " RANGA RAO ", " BALAKRISHNA ", " A.SRINIVASA ", " GOPARAJU ", " SRIDHAR REDDY ", " BHOOPINDER SINGH ", " SREEDHAR/SIDHARTH ", " V.ANANDH PRASAD ", " SHASHIDAR REDDY ", " PANDURANGA REDDY ", " ASHOK VARADHAN REDDY ", " SUNIL REDDY ", " KUMAR ", " RAMAKRISHNA PRASAD ", " K.S RAO "};
    public static final String[] phoneNormal = {" 9849001315 ", " 9866773300 ", "  9848799189 ", " 9490793339 ", " 9849452812 ", " 9848991979 ", " 23396191 ", " 9246244315 ", " 9030010112 ", " 9849024580 ", " 9948123838 ", " 8008503972 ", " 9441115599 ", " 8008018888 ", " 9393998989 ", " 9989268487 ", " 2N3N552123 ", " 23556001", " 23556070", " 23358111"};
    public static final String[] emailNormal = {" rafath19@gmail.com ", " info@pragatiresorts.com ", " jaiprakash@rkestates.com ", " info@royalhomeconstructins.com ", " sriadityahomes@rediffmail.com ", " srinivasacon@satyam.net.in ", " info@srrprojects.com ", " bhip2007@gmail.com ", " sridhar.bathula@adityacc.com ", " purchase@bhavyaconstructions.in ", " email@choice-india.com ", " info@giridhariconstructions.com ", " info@greenviewinfra.com ", " adil@headwaygroup.in ", " info@ivrinfra.com ", " hyhrd@madhucon.com ", " info@mahindharaprojects.com ", " info@meenakshigroup.com ", " rafath19@gmail.com "};

    //Pream BuildExpo project

    public static final String[] companyNamePremium = {" PBSR DEVELOPERS PVT LTD ", " PRADEEP CONSTRUCTIONS ", " PRATHIMA ESTATES LTD  ", " RVR PROJECTS PVT LTD ", " S&S GREEN PROJECTS PVT LTD ", " SUVARNA BHOOMI DEVELOPERS PVT LTD ", " V SQUARE DEVELOPERS ", " ARVEE ASSOCIATES ", " ABHINANDNA HOUSING PVT LTD  ", " ACADEMY OF CONSTRUCTION TECHNOLOGY ", " AK ASSOCIATES ", " ANAND BUILDERS@CONTRACTOR ", " APURUPA CONSTRUCTIONS PVT LTD ", " HARITHA VANAM ", " BRINDAVAN DEVELOPERS PVT LTD ", " CHENNAKESHAVA CONSTRUCTIONS ", " HRH CONSTRUCTIONS ", " JANACHAITANYA HOUSING PVT LTD ", " KWALITY CONSTRUCTIONS ENGG ", " MAA BUILDERS&CONTRACTORS ", " MAHESH PLOTS PVT LTD ", " MANJEERA CONSTRUCTIONS PVT LTD ", " PAVANI ESTATES ", " RISHIS SAI RAM PROJECTS PVT LTD ", " SAI NIKITHA ESTATES PVT LTD ", " SPACE VISION EDIFICE ", " SREENIVASA ASSOCIATES PROJECT WORK LTD ", " SRI SAI CONSTRUCTIONS&DEVELOPERS "};
    public static final String[] contactPersonPremium = {" RAMESH KUMAR ", " B.PRADEEP REDDY ", " B.SRINIVASA RAO ", " GOPI KRISHNA ", " RAJ KUMAR ", " SRINIVAS ", " SHASHIDAR REDDY ", " CHAKRAPANI ", " SURENDRANATH ", " NANDAN ", " M.A.KHAISER ", " ANAND RAO ", " ANIL REDDY ", " PRASANA KUMAR  ", " MURALI KRISHNA ", " NARENDAR BABU.R ", " RAVINDRA BABU ", " M.SUDHAKAR ", " V.SUDHAKAR ", " ANAND RAO ", " MAHESH ", " YOGANAND ", " NARASHIMHA REDDY ", " MADHUSUDHAN RAO ", " SHIVARAM ", " MURALI ", " T.V.S SHARMA ", " VINOD YADAV "};
    public static final String[] phonePremium = {" 7799881247 ", " 23556449 ", " 23554125 ", " 9010204129 ", " 9052252222 ", " 42435555 ", " 67114362 ", " 23737633 ", " 9392626719 ", " 9642362436 ", " 9849099886 ", " 9849150654 ", " 9246535845 ", " 9949220304 ", " 9849020278 ", " 9849458686 ", " 66105031 ", " 23417612 ", " 9948099188 ", " 9849150654 ", " 7416176799 ", " 23735194 ", " 9848098489 ", " 65197899 ", " 9959336666 ", " 9849172244 ", " 66630121 ", " 9885667826 "};
    public static final String[] emailPremium = {" rameshkumar.hyd@patelrealty.in ", " info@pradeepconstructions.com ", " info@prathimagroup.net ", " rvrhyd@rvrprojects.com ", " info@ssgreenprojects.com ", " info@suvarnabhoomi.in ", " shashigone@gmail.com ", " aarvee@aarvee.net ", " hyderbad@abhinandana.com ", " actedesk@gmail.com ", " akassociates_arch@yahoo.com ", " anandnr2000@yahoo.com ", " apurupainfra@gmail.com ", " guadiyaram@gmail.com ", " y_murali99@yahoo.com ", " chennakeshava_constructions@yahoo.com ", " kwalityhyderabad@gmail.com ", " anandnr2000@yahoo.com ", " mahesh@maheshplots.com ", " maruthicrop@gmail.com ", " pavaniestates@gmail.com ", " info@rsrppl.com ", " asivaramireddy@gmail.com ", " seenivasa_associates@yahoo.com ", " www.sreenivasabuilders.com ", " vinodgundaboina@gmail.com "};

    //Gold BuildExpo project
    public static final String[] companyNameGold = {" UNITY BUILDERS&DEVELOPERS ", " VSK INFRA PROJECTS LTD ", " MUPPA HOMES PVT LTD  ", " ALEKHYA CONSTRUCTIONS LYD ", " APR CONSTRUCTIONS LTD ", " ARKAY BUILDERS ", " JAI MATA DI VILLAS PVT LTD ", " LAKSHMI CONSTRUCTIONS ", " LUMBINI CONSTRUCTIONS LTD ", " NAVAKETAN ENTERPRISES ", " PAVITHRA BHOOMI DEVELOPERS ", " RAY ASSOCIATES ", " RB GROUP ", " ROARK ENTERPRISES PVT LTD ", " SAYEBAAN CONSTRUCTIONS  ", " SHIRYA CONSTRUCTIONS ", " SMR BUILDERS PVT LTD ", " SRI DURGA ESTATES ", " SRIKAR CONSTRUCTIONS ", " SSR HOMES ", " TITUS PROPERTIES PVT LTD ", " TUSHAR CONSTRUCTIONS&INTERIORS ", " KARTHIK CONSTRUCTIONS ", " ANIL CONSTRUCTIONS ", " APPLE HOMES ", " BRC INFRA PVT LTD ", " COMFORT HOMES& RESORTS PVT LTD ", " CONCREATE CONSTRUCTIONS ", " CYBER CITY BUILDERS&DEVELOPERS "};
    public static final String[] contactPersonGold = {" MURALI KRISHNA ", " SURESH ", " SRIKANTH ", " ADITYA MITTA ", " PRABHAKAR REDDY ", " APPA RAO ", " MURALI RETINENI ", " VENKAT REDDY ", " SUKENDER REDDY ", " RAJEEV BHARGAV ", " SEETHIAH  ", " RAIDU ", " BALACHARY ", " PRABHAKAR REDDY ", " SYED GHOUSE ALI ", " KAPIL ", " RAMI REDDY ", " NARAYANA ", " RAVI SHENKAR ", " R.B RAO ", " SRINIVAS ", " SIVA SHANKAR REDDY ", " RAMKUMAR ", " ANIL KUMAR ", " RAVI ", " B.RAMESH ", " BANGAR RAJU ", " PRAVEEN REDDY ", " NAROTHAM REDDY "};
    public static final String[] phoneGold = {" 9849020278 ", " 9246522777 ", " 9885999996 ", " 9248003369 ", " 23813833 ", " 9246268040 ", " 9966211888 ", " 9246811421 ", " 23311224 ", " 9391123904 ", " 934322779 ", " 9849928278 ", " 9848016620 ", " 9492035778 ", " 9391004873 ", " 9704882895 ", " 23353722 ", " 23403040 ", " 9391007977 ", " 9866662275 ", " 9603546768 ", " 9848533322 ", " 9246540132 ", " 9885810111 ", " 67119118 ", " 9849001133 ", " 9849261328 ", " 9676200000 ", " 9989424444 "};
    public static final String[] emailGold = {" y_murali99@yahoo.com ", " viswaproperties@gmail.com ", " muppahomes@gmail.com ", " aditya.mitta@alekhyaconstructions.com ", " info@aprcl.com ", " sales@jmdvillas.com ", " info@laksmicomstructions.in ", " yelapati@yahoo.co.in ", " rajeev.b.neco@gmail.com ", " rayer.99@gmail.com ", " r_bala2chary@yahoo.com ", " prabhakar.roak@roarkenterprises.com ", " zans_syed@yahoo.com ", " support@shriyaconstructions.com ", " info@smrholdings.in ", " sdestates@yahoo.com ", " ravisekhar23@gmail.com ", " sreenuk2004@yahoo.com ", " sdestates@yahoo.com ", " tusharinteriors@gmail.com ", " koneru1@gmail.com ", " www.applehomes.com ", " br_constructions@yahoo.com ", " homesandresorts@gmail.com ", " praveentammireddy@gmail.com ", " info@rainbowvistas.in "};

    //Hot  project BuildExpo project
    public static final String[] companyNameHotProject = {" GIRIJA BUILDERS PVT LTD  ", " HAPPY HOMES ESTATES ", " HYTEH PROJECTS ", " ONDU PROJECTS LTD  ", " LODHA MERIDIAN ", " MEGHANA CONSTRUCTIONS ", " MURALI CONSTRUCTIONS ", " KAKATIYA CONSTRCTIONS ", " NAVINOS HOMES&PROJECTS PVT LTD ", " PRIME CONSTRUCTIONS ", " SARVAGNYA CONSTRUCTIONS ", " SP CONSULTANTS ", " SRI JYOTHSNA ASSOCIATES ", " SRINIVASA.NN ", " VERTEX HOMES PVT LTD ", " YOGITHA CONSTRUCTIONS ", " OM SHAKTI BUILDERS ", " ANNAPURANA BUILDERS ", " LANDMARK BUILDERS ", " PREECON CONSTRUCTIONS ", " PRASAD&COMPANY LTD ", " SEW INFRASTRUCTURE LTD ", " SRI BALAJI CONSTRUCTIONS ", " SRI RAGHAVA CONSTRUCTIONS ", " SV CONSTRUCTIONS ", " SV PROPERTIES ", " ELAN INFRASTRUCTURES PVT LTD ", " HSC CONSTRUCTIONS ", " BHARANIKANTH INFRASTRUCTURES PVT LTD ", " BRICKS N STONE BUILDERS ", " MARUTHI HOMES ", " MUKUNDA CONSTRUCTIONS ", " RUDRA SREE HOUSING PVT LTD  "/*, " SAHITHI BUILDERS ", " SRI VENKATESHWARACONSTRN "*/};
    public static final String[] contactPersonHotProject = {" P.SUBBA RAO ", " P.SATISH KUMAR ", " RAGHURAM ", " SHYAM PRASAD REDDY ", " R.KARTHIK ", " NARASHIMA RAO KOTHA ", " MURALI ", " SRINIVASA RAO ", " VINOD REDDY ", " VENKATESHWARA RAO ", " B.S.N.MURTHY ", " SIVA PRASAD REDDY ", " RADHA KRISHNA ", " SRINIVASA ", " VERMA ", " KANTHA RAO ", " PRAKASH ", " SURAJ PRASAD AGARWAL ", " VEERENDER ", " PREM CHAND ", " RAMA SWAMY ", " RAJSHEKAR ", " SATHISH ", " VENKATESHWAR RAO ", " SRINIVAS REDDY ", " RAMANA ", " VENKATA PRASAD ", " CHANDRA SHEKHAR ", " SATYAVATHI ", " VINOD KUMAR ", " RAJENDRA PRASAD ", " R.R.KOTI ", " SRINIVAS ", " SRINIVAS ", " VENKATESHWARA CHARY "};
    public static final String[] phoneHotProject = {" 9949038160 ", " 9032158338 ", " 9866445454 ", " 44780000 ", " 9000785605 ", " 9299996988 ", " 9246548947 ", " 9440054958 ", " 9885126868 ", " 23069000 ", " 9849029313 ", " 9246506534 ", " 9949174788 ", " 917739779 ", " 23155731 ", " 23060893 ", " 9959366648 ", " 99000846111 ", " 8686000111 ", " 9440801863 ", " 23413687 ", " 23402153 ", " 9032566576 ", " 27768297 ", " 9246548693 ", " 9247408227 ", " 66832783 ", " 9000002522 ", " 9246330554 ", " 66313144 ", " 9849036438 ", " 24066711 ", " 24043353 ", " 9246542965 ", " 9848803785 "};
    public static final String[] emailHotProject = {" girijabuilersmd@gmail.com ", " happyhomesdesigners@gmail.com  ", " raghurammadi@gmail.com ", " mamatha.y@induprojects.com ", " info@lodhagroup.com ", " meghanaconstructions@gmail.com ", " muralikpuli@gmail.com ", " navinosconstructions@yahoo.com ", " saravnyaconstructions@gmail.com ", " sp_consults@yahoo.com ", " srijyothsnaassociates@gmail.com ", " nsrinivasa.cc@gmail.com ", " nsrinivasa.cc@gmail.com ", " info@vertexhomes.com ", " madhavaramk@yahoo.com ", " venu_prakash2004@yahoo.com ", " whitehousehyd@hotmail.com ", " sriraghavaconstructions@gmail.com ", " info@preeconconstructions.co.in ", " info@preeconconstructions.co.in ", " mail@sewinfrastructure.com ", " info@dslinfra.com ", " sriraghavaconstructions@gmail.com ", " ansrinivasreddy@gmail.com ", " dslinfra@gmail.com ", " elan.infra@gmail.com ", " hscconstructions@yahoo.com ", " satyavathi_tvn@rediffmail.com ", " infra@bnsbuilders.com ", " prasadbadam_5477@yahoo.com ", " rrkoti@gmail.com ", " contact@rudrasree.com ", " sahithibuilders@gmail.com ", " srivenconst@gmail.com "};

    //Notifications
    public static final String[] companyNameNotification = {" THE HOUSE OF INTERIORS ", " VIEW CREATIONS ", " VIJAYA DURGA CONSTRUCTIONS PVT LTD ", " VS CONSTRUCTIONS ", " AYYAPPA CONSTRUCTIONS CONSULTANCY ", " ETERNAL BUILDERS ", " 24-SERVICE POINT ", " VEERA SIVA SAI CONSTRUCTIONS PVT LTD ", " AMBIENCE CONSTS INDIA LTD ", " AMULYA CONSTRUCTIONS&INFRASTRUCTURE ", " BHARATH CONSULTANTS ", " GREEN HOME ", " HASSAN&ASSOCIATES ", " JS CONTRACTORS&CONSULTANTS PVT LTD ", " KHADRI CONSTRUCTIONS ", " MERIDIAN HOMES ", " PRARMOUNT CONSTRUCTIONS CO ", " RADHA REALTY CORPPVT LTD ", " RKI BUILDERS PVT LTD ", " SITRUS PROJECTS ", " SREE MITRA TOWNSHIPS PVT LTD ", " SAFEWAY ", " SKYLA "/*, " BOTANIKA ", " VENKY INFRA public LIMITED "*/};
    public static final String[] contactPersonNotification = {" SHIVA KUMAR ", " JAVEED ", " VENKATESHWAR REDDY ", " VENKAT SURESH ", " SRINIVAS RAO ", " MAHESH KUMAR ", " SAI KUMAR  ", " SHIVA KUMAR ", " GOVARDAN REDDY ", " ARUNKUMAR/LAXMAN ", " SURENDER ", " HARI BABU ", " HASSAN.A.RAHIM ", " SRAVAN KUMAR REDDY ", " S.M.KHADRI ", " NARASHIMA RAO ", " DINESH SHANKAR ", " RAVINDRANATH REDDY ", " KISHORE KUMAR ", " RAJU ", " CHOWDARY ", " K.NITIN CHANDRA ", " SRINATH LYER ", " G.SYRYANARAYANA RAJU "};
    public static final String[] dateTimeNotification = {" srivenconst@gmail.com ", " thehouseofinteriors.hyd@gmail.com ", " nvreddy2266@gmail.com ", " suresh_vsconstructions@yahoo.com ", " bolla_chari@yahoo.com ", " mahesh.bandaru@gmail.com ", " saikumar783@gmail.com ", " ambience_constructions@yahoo.com ", " info@amulyaconstructins.com ", " www.bharathconsultancy.com ", " greenhomesite@hotmail.com ", " hassan.a.rahim@gmail.com ", " sravan13@yahoo.com  ", " khadrishamila@hotmail.com ", " info@meridianhomeshyderabad.com ", " paramountconst01@yahoo.com ", " www.radharealty.com ", " rkibuilderspvtltd@yahoo.com ", " info@sitursgroup.com ", " info@sreemitragroup.com ", " info@safewayinfra.in ", " reservations@skyla.co ", " siyer@botanika.in ", " venkyinfra13@gmail.com "};


}
